### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by larsvoigt** [daisy/pipeline-assembly#111]
Hi, 
I have tried to build a Debian package with:
```
mvn clean package -P deb
```
then maven stop the work process and has raised an error. The reason is: it can't get this 
``org.daisy.dotify:dotify.formatter.impl:jar:2.5.0``  library.
Our firewall is blocking the download and  mean it is a virus. 
![unbenannt](https://cloud.githubusercontent.com/assets/8373218/17437472/32eca174-5b1e-11e6-8ffb-55fb8da2894e.PNG)

It is a virus???

Lars

**Comment by josteinaj** [comment]
It's very unlikely that it's been infected, but it's strange that it thinks it is. Does it happen also when you download the JAR directly from a web browser?
http://repo.maven.apache.org/maven2/org/daisy/dotify/dotify.formatter.impl/2.5.0/dotify.formatter.impl-2.5.0.jar

And what happens if you download the JAR from another site?
http://search.maven.org/remotecontent?filepath=org/daisy/dotify/dotify.formatter.impl/2.5.0/dotify.formatter.impl-2.5.0.jar

**Comment by larsvoigt** [comment]
Thanks @josteinaj. The second link works fine. Okay I think Sophos is not consistent how downloads will be handled. It looks like not for a deep inspection of the package.  Now I have tested to download also other packages  form daisy repro and all works fine. It is curious.

**Comment by larsvoigt** [comment]
@josteinaj, Do you have experience with the dp2 under linux? Please can you contact me lars.voigt@dzb.de.

**Comment by josteinaj** [comment]
@larsvoigt Yes I'm using Ubuntu. I'll send you a mail, but also feel free to discuss here in this issue thread or on the [developers mailinglist](https://groups.google.com/forum/#!forum/daisy-pipeline-dev) in case others have something to add as well.

**Comment by larsvoigt** [comment]
Thanks @josteinaj. I close this issues. Because it's a local problem on our side. I don't know why Sophos think it's a virus. It'll be still their secret...
